name: Push to Replicate

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  push-to-replicate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Cog
        uses: replicate/setup-cog@v2
        with:
          token: ${{ secrets.REPLICATE_CLI_AUTH_TOKEN }}
          install-cuda: false

      - name: Push model to Replicate
        run: |
          cog push r8.im/ani0135/chatbot
